name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Make libft
      run: make -C libft
    - name: Make minishell
      run: make
